// GENERATED by flxc from accounts.flx.
// Do not edit by hand — your changes will be overwritten.
// ignore_for_file: unused_import, prefer_const_constructors,
// ignore_for_file: unnecessary_brace_in_string_interps,
// ignore_for_file: prefer_single_quotes, directives_ordering,
// ignore_for_file: lines_longer_than_80_chars,
// ignore_for_file: require_trailing_commas,
// ignore_for_file: prefer_const_literals_to_create_immutables

import 'package:flutter/material.dart';

import 'package:flx_runtime/flx_runtime.dart';
import '../data/overview_view_models.dart';
import '../domain/models.dart';

@page('/accounts')
class AccountsScreen extends Composable {
  const AccountsScreen({super.key});

  @override
  Widget build(BuildContext context) {
    final vm = useViewModel<AccountsViewModel>();
    final nav = useNavigator();
    final name = useTextField();
    final open = useTextField();

    return Screen(
      title: "Accounts",
      subtitle: "Net worth ${vm.netWorth.format()}",
      scrollable: true,
      children: [
        Panel(
          title: "Your accounts",
          children: [
            if (vm.accounts.isEmpty) ...[
              Text("No accounts yet", style: Styles.caption),
            ] else ...[
              for (final account in vm.accounts) ...[
                Tile(title: account.name, subtitle: "${account.kind.label} · ${vm.transactionCount(account.id)} transactions", trailing: vm.balanceLabel(account), onTap: () => nav.toPath("/accounts/${account.id}")),
              ],
            ],
          ],
        ),
        Panel(
          title: "Add an account",
          children: [
            Field(controller: name, label: "Name", error: vm.nameError),
            Field(controller: open, label: "Opening balance", prefix: "\$", keyboard: TextInputType.number),
            Button("Add account", () {
              vm.addAccount(name.text, AccountKind.checking, open.text).then((added) {
              if (added) {
              name.clear();
              open.clear();
              }
              });
            }),
          ],
        ),
      ],
    );
  }
}

@page('/accounts/:id')
class AccountDetailScreen extends Composable {
  const AccountDetailScreen({required this.id, super.key});

  final String id;

  @override
  Widget build(BuildContext context) {
    final vm = useViewModel<AccountsViewModel>();
    final nav = useNavigator();

    return Screen(
      title: vm.account(id)?.name ?? "Account",
      subtitle: vm.balanceOf(id).format(),
      children: [
        Panel(
          children: [
            [
              Stat(value: vm.balanceOf(id).format(), label: "Balance"),
              Stat(value: "${vm.transactionCount(id)}", label: "Transactions"),
            ].row(main: MainAxisAlignment.spaceBetween),
          ],
        ),
        LazyColumn(items: vm.transactionsFor(id), gap: 4, empty: EmptyState(title: "No transactions", subtitle: "Nothing has been recorded against this account"), itemBuilder: (tx, _) => Tile(title: tx.note.isEmpty ? vm.categoryName(tx) : tx.note, subtitle: "${vm.categoryName(tx)} · ${formatRelativeDate(tx.date)}", trailing: tx.kind == TxKind.income ? tx.amount.format(showSign: true) : "-${tx.amount.format()}", onTap: () => nav.toPath("/transactions/${tx.id}"))).expanded(),
      ],
    );
  }
}
