// GENERATED by flxc from categories.flx.
// Do not edit by hand — your changes will be overwritten.
// ignore_for_file: unused_import, prefer_const_constructors,
// ignore_for_file: unnecessary_brace_in_string_interps,
// ignore_for_file: prefer_single_quotes, directives_ordering,
// ignore_for_file: lines_longer_than_80_chars,
// ignore_for_file: require_trailing_commas,
// ignore_for_file: prefer_const_literals_to_create_immutables

import 'package:flutter/material.dart';

import 'package:flx/flx.dart';
import '../data/overview_view_models.dart';
import '../data/ledger_repository.dart';

@page('/categories')
class CategoriesScreen extends Composable {
  const CategoriesScreen({super.key});

  @override
  Widget build(BuildContext context) {
    final vm = useViewModel<CategoriesViewModel>();
    final budget = useTextField(text: vm.editingId == null ? "" : vm.initialBudgetText(vm.editingId!));
    final name = useTextField();

    return Screen(
      title: "Categories",
      subtitle: vm.periodLabel,
      scrollable: true,
      children: [
        if (vm.overBudgetCount > 0) ...[
          Panel(
            children: [
              Text("${vm.overBudgetCount} categories are over budget this month", style: Styles.body),
            ],
          ),
        ],
        Panel(
          title: "Spending and budgets",
          children: [
            for (final line in vm.lines) ...[
              [
                [
                  [
                    Dot(Color(line.category.colorValue)),
                    Text(line.category.name, style: Styles.body),
                  ].row(gap: 8),
                  Text(vm.budgetLabel(line), style: Styles.caption),
                ].row(main: MainAxisAlignment.spaceBetween),
                if (line.hasBudget) ...[
                  ProgressBar(line.fraction, color: Color(line.category.colorValue), isOver: line.isOver),
                ],
                if (vm.editingId == line.category.id) ...[
                  [
                    Field(controller: budget, label: "Monthly budget", prefix: "\$", keyboard: TextInputType.number, error: vm.budgetError).expanded(),
                    Button("Save", () {
                      vm.saveBudget(line.category.id, budget.text);
                    }),
                    Button("Cancel", () {
                      vm.cancelEditing();
                    }),
                  ].row(gap: 8),
                ] else ...[
                  Button(line.hasBudget ? "Change budget" : "Set a budget", () {
                    vm.startEditing(line.category.id);
                  }),
                ],
              ].column(gap: 4, cross: CrossAxisAlignment.start),
            ],
          ],
        ),
        Panel(
          title: "Add a category",
          children: [
            Field(controller: name, label: "Name"),
            Button("Add category", () {
              vm.addCategory(name.text, 0xFF7E57C2).then((added) {
              if (added) name.clear();
              });
            }),
          ],
        ),
      ],
    );
  }
}
