// GENERATED by flxc from dashboard.flx.
// Do not edit by hand — your changes will be overwritten.
// ignore_for_file: unused_import, prefer_const_constructors,
// ignore_for_file: unnecessary_brace_in_string_interps,
// ignore_for_file: prefer_single_quotes, directives_ordering,
// ignore_for_file: lines_longer_than_80_chars,
// ignore_for_file: require_trailing_commas,
// ignore_for_file: prefer_const_literals_to_create_immutables

import 'package:flutter/material.dart';

import 'package:flx_runtime/flx_runtime.dart';
import '../data/overview_view_models.dart';
import '../data/ledger_repository.dart';
import 'insights.dart';

class BudgetRow extends Composable {
  const BudgetRow({required this.line, super.key});

  final BudgetLine line;

  @override
  Widget build(BuildContext context) {
    return [
      [
        Text(line.category.name, style: Styles.body),
        Text("${line.spent.format()} of ${line.budget!.format()}", style: Styles.caption),
      ].row(main: MainAxisAlignment.spaceBetween),
      ProgressBar(line.fraction, color: Color(line.category.colorValue), isOver: line.isOver),
    ].column(gap: 4, cross: CrossAxisAlignment.start);
  }
}

@page('/')
class DashboardScreen extends Composable {
  const DashboardScreen({super.key});

  @override
  Widget build(BuildContext context) {
    final vm = useViewModel<DashboardViewModel>();
    final nav = useNavigator();

    return Screen(
      title: "Ledger",
      subtitle: vm.periodLabel,
      scrollable: true,
      actionIcon: Icons.settings,
      onAction: () => nav.toPath("/settings"),
      actionTooltip: "Settings",
      fabIcon: Icons.add,
      onFab: () => nav.toPath("/transactions/new"),
      fabLabel: "Add",
      children: [
        [
          Button("← Previous", () {
            vm.previousMonth();
          }),
          Button("Next →", () {
            vm.nextMonth();
          }),
        ].row(main: MainAxisAlignment.spaceBetween),
        Panel(
          children: [
            [
              Stat(value: vm.spent.format(), label: "Spent"),
              Stat(value: vm.earned.format(), label: "Earned"),
              Stat(value: vm.net.format(showSign: true), label: "Net"),
            ].row(main: MainAxisAlignment.spaceBetween, cross: CrossAxisAlignment.start),
          ],
        ),
        Panel(
          title: "Net worth",
          children: [
            Text(vm.netWorth.format(), style: Styles.title),
            for (final account in vm.accounts) ...[
              Tile(title: account.name, subtitle: account.kind.label, trailing: vm.balanceOf(account.id).format(), onTap: () => nav.toPath("/accounts/${account.id}"), dense: true),
            ],
          ],
        ),
        Panel(
          title: "Budgets",
          children: [
            if (vm.budgets.isEmpty) ...[
              Text("No budgets set for this month", style: Styles.caption),
            ] else ...[
              ProgressBar(vm.budgetFraction, height: 10),
              for (final line in vm.budgets) ...[
                BudgetRow(line: line),
              ],
            ],
          ],
        ),
        Panel(
          title: "Recent",
          children: [
            if (vm.recent.isEmpty) ...[
              Text("Nothing recorded this month", style: Styles.caption),
            ] else ...[
              for (final tx in vm.recent) ...[
                Tile(title: tx.note, subtitle: vm.categoryName(tx), trailing: tx.amount.format(), leading: Dot(Color(vm.categoryColor(tx))), onTap: () => nav.toPath("/transactions/${tx.id}"), dense: true),
              ],
            ],
            Button("See all transactions", () {
              nav.toPath("/transactions");
            }),
          ],
        ),
        [
          Button("Accounts", () {
            nav.toPath("/accounts");
          }),
          Button("Categories", () {
            nav.toPath("/categories");
          }),
        ].row(gap: 8),
        Button("Insights", () {
          nav.to(InsightsScreen());
        }),
      ],
    );
  }
}
