// GENERATED by flxc from insights.flx.
// Do not edit by hand — your changes will be overwritten.
// ignore_for_file: unused_import, prefer_const_constructors,
// ignore_for_file: unnecessary_brace_in_string_interps,
// ignore_for_file: prefer_single_quotes, directives_ordering,
// ignore_for_file: lines_longer_than_80_chars,
// ignore_for_file: require_trailing_commas,
// ignore_for_file: prefer_const_literals_to_create_immutables

import 'package:flutter/material.dart';

import 'package:flx_runtime/flx_runtime.dart';
import '../data/insights.dart';
import '../domain/money.dart';

class TrendBar extends Composable {
  const TrendBar({required this.month, required this.peak, super.key});

  final MonthlyTotal month;
  final Money peak;

  @override
  Widget build(BuildContext context) {
    return [
      [
        Text(month.period.shortLabel, style: Styles.caption),
        Text(month.spent.format(), style: Styles.caption),
      ].row(main: MainAxisAlignment.spaceBetween),
      ProgressBar(month.heightAgainst(peak), height: 6),
    ].column(gap: 4, cross: CrossAxisAlignment.start);
  }
}

class InsightsBody extends Composable {
  const InsightsBody({super.key});

  @override
  Widget build(BuildContext context) {
    final service = useInject<InsightsService>();
    final report$ = useFetch(service.buildReport);

    return report$.when(
      loading: () => const Center(child: CircularProgressIndicator()),
      error: (error) => Center(child: Text('Error: $error')),
      data: (report) {
        return [
          if (report.isEmpty) ...[
            EmptyState(title: "Nothing to report yet", subtitle: "Record a few transactions and come back"),
          ] else ...[
            Panel(
              title: "At a glance",
              children: [
                [
                  Stat(value: report.averageMonthlySpend.format(), label: "Average month"),
                  Stat(value: "${report.transactionCount}", label: "Transactions"),
                ].row(main: MainAxisAlignment.spaceBetween, cross: CrossAxisAlignment.start),
                if (report.busiestMonth != null) ...[
                  Text("Busiest month was ${report.busiestMonth!.label}", style: Styles.caption),
                ],
                if (report.largestExpense != null) ...[
                  Text("Largest single expense: ${report.largestExpense!.amount.format()} on ${report.largestExpense!.note}", style: Styles.caption),
                ],
              ],
            ),
            Panel(
              title: "Last 12 months",
              children: [
                for (final month in report.trend) ...[
                  TrendBar(month: month, peak: report.peakSpend),
                ],
              ],
            ),
            Panel(
              title: "Where it goes",
              children: [
                for (final slice in report.breakdown) ...[
                  [
                    [
                      [
                        Dot(Color(slice.category.colorValue)),
                        Text(slice.category.name, style: Styles.body),
                      ].row(gap: 8),
                      Text("${slice.spent.format()} · ${slice.percentLabel}", style: Styles.caption),
                    ].row(main: MainAxisAlignment.spaceBetween),
                    ProgressBar(slice.share, color: Color(slice.category.colorValue), height: 6),
                  ].column(gap: 4, cross: CrossAxisAlignment.stretch),
                ],
              ],
            ),
          ],
        ].column(gap: 20, cross: CrossAxisAlignment.stretch);
      },
    );
  }
}

@page('/insights')
class InsightsScreen extends Composable {
  const InsightsScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Screen(
      title: "Insights",
      subtitle: "Across the last year",
      scrollable: true,
      children: [
        InsightsBody(),
      ],
    );
  }
}
