// GENERATED by flxc from lock.flx.
// Do not edit by hand — your changes will be overwritten.
// ignore_for_file: unused_import, prefer_const_constructors,
// ignore_for_file: unnecessary_brace_in_string_interps,
// ignore_for_file: prefer_single_quotes, directives_ordering,
// ignore_for_file: lines_longer_than_80_chars,
// ignore_for_file: require_trailing_commas,
// ignore_for_file: prefer_const_literals_to_create_immutables

import 'package:flutter/material.dart';

import 'package:flx/flx.dart';
import '../data/session_view_models.dart';

class Key extends Composable {
  const Key({required this.vm, required this.digit, super.key});

  final LockViewModel vm;
  final String digit;

  @override
  Widget build(BuildContext context) {
    return Button(digit, () {
      vm.press(digit);
    });
  }
}

@page('/lock')
class LockScreen extends Composable {
  const LockScreen({super.key});

  @override
  Widget build(BuildContext context) {
    final vm = useViewModel<LockViewModel>();
    final nav = useNavigator();

    return Screen(
      title: "Locked",
      showBack: false,
      children: [
        Text("Enter your PIN", style: Styles.subtitle),
        Text("●" * vm.entryLength, style: Styles.title),
        if (vm.message != null) ...[
          Text(vm.message!, style: Styles.caption),
        ],
        for (final row in const[["1", "2", "3"], ["4", "5", "6"], ["7", "8", "9"]]) ...[
          [
            for (final digit in row) ...[
              Key(vm: vm, digit: digit),
            ],
          ].row(gap: 8, main: MainAxisAlignment.center),
        ],
        [
          Button("Clear", () {
            vm.clearEntry();
          }),
          Key(vm: vm, digit: "0"),
          Button("⌫", () {
            vm.backspace();
          }),
        ].row(gap: 8, main: MainAxisAlignment.center),
        Button(vm.isLockedOut ? "Locked out" : "Unlock", () {
          if (vm.submit()) nav.toPath("/");
        }),
      ],
    );
  }
}
