// GENERATED by flxc — the app route table.
// Do not edit by hand — your changes will be overwritten.

import 'package:flx_runtime/flx_runtime.dart';
import 'accounts.dart';
import 'categories.dart';
import 'dashboard.dart';
import 'insights.dart';
import 'lock.dart';
import 'settings.dart';
import 'transaction_form.dart';
import 'transactions.dart';

/// Every @page composable, keyed by its route pattern.
final appRoutes = <RouteDef>[
  RouteDef('/', (params) => const DashboardScreen()),
  RouteDef('/accounts', (params) => const AccountsScreen()),
  RouteDef('/categories', (params) => const CategoriesScreen()),
  RouteDef('/insights', (params) => const InsightsScreen()),
  RouteDef('/lock', (params) => const LockScreen()),
  RouteDef('/settings', (params) => const SettingsScreen()),
  RouteDef('/transactions', (params) => const TransactionsScreen()),
  RouteDef('/transactions/new', (params) => const NewTransactionScreen()),
  RouteDef('/accounts/:id', (params) => AccountDetailScreen(id: params['id'] ?? '')),
  RouteDef('/transactions/:id', (params) => EditTransactionScreen(id: params['id'] ?? '')),
];

