// GENERATED by flxc from settings.flx.
// Do not edit by hand — your changes will be overwritten.
// ignore_for_file: unused_import, prefer_const_constructors,
// ignore_for_file: unnecessary_brace_in_string_interps,
// ignore_for_file: prefer_single_quotes, directives_ordering,
// ignore_for_file: lines_longer_than_80_chars,
// ignore_for_file: require_trailing_commas,
// ignore_for_file: prefer_const_literals_to_create_immutables

import 'package:flutter/material.dart';

import 'package:flx/flx.dart';
import '../data/session_view_models.dart';

@page('/settings')
class SettingsScreen extends Composable {
  const SettingsScreen({super.key});

  @override
  Widget build(BuildContext context) {
    final vm = useViewModel<SettingsViewModel>();
    final nav = useNavigator();
    final pin = useTextField();
    final confirm = useTextField();

    return Screen(
      title: "Settings",
      scrollable: true,
      children: [
        Panel(
          title: "Appearance",
          children: [
            Toggle(vm.darkMode, label: "Dark mode", (on) {
              vm.setDarkMode(on);
            }),
          ],
        ),
        Panel(
          title: "Security",
          children: [
            Text(vm.hasPin ? "A PIN is set. It is asked for on every launch.": "No PIN set — the ledger opens straight away.", style: Styles.caption),
            Field(controller: pin, label: "New PIN", obscure: true, keyboard: TextInputType.number, error: vm.pinError),
            Field(controller: confirm, label: "Confirm PIN", obscure: true, keyboard: TextInputType.number),
            Button("Set PIN", () {
              vm.setPin(pin.text, confirm.text).then((ok) {
              if (ok) {
              pin.clear();
              confirm.clear();
              }
              });
            }),
            if (vm.hasPin) ...[
              Button("Remove PIN", () {
                vm.removePin();
              }),
              Button("Lock now", () {
                vm.lockNow();
                nav.toPath("/lock");
              }),
            ],
            if (vm.status != null) ...[
              Text(vm.status!, style: Styles.caption),
            ],
          ],
        ),
        Panel(
          title: "Data",
          children: [
            Text("Resetting wipes every transaction and reinstates the sample ledger.", style: Styles.caption),
            Button("Reset ledger", () {
              vm.resetLedger();
            }),
          ],
        ),
      ],
    );
  }
}
