// GENERATED by flxc from transaction_form.flx.
// Do not edit by hand — your changes will be overwritten.
// ignore_for_file: unused_import, prefer_const_constructors,
// ignore_for_file: unnecessary_brace_in_string_interps,
// ignore_for_file: prefer_single_quotes, directives_ordering,
// ignore_for_file: lines_longer_than_80_chars,
// ignore_for_file: require_trailing_commas,
// ignore_for_file: prefer_const_literals_to_create_immutables

import 'package:flutter/material.dart';

import 'package:flx/flx.dart';
import '../data/transactions_view_models.dart';
import '../domain/models.dart';

class TransactionForm extends Composable {
  const TransactionForm({required this.id, super.key});

  final String id;

  @override
  Widget build(BuildContext context) {
    final vm = useViewModel<TransactionFormViewModel>();
    final form = useMemoized(() => vm.opened(id), [id]);
    final nav = useNavigator();
    final amount = useTextField(text: form.initialAmountText(id));
    final note = useTextField(text: form.initialNoteText(id));

    return Screen(
      title: form.title,
      scrollable: true,
      children: [
        Segmented(form.kind, TxKind.values, labelOf: (k) => k.label, (kind) {
          form.setKind(kind);
        }),
        Field(controller: amount, label: "Amount", prefix: "\$", keyboard: TextInputType.number, autofocus: true, error: form.amountError(amount.text)),
        Picker(form.accountId, form.accounts.map((a) => a.id).toList(), labelOf: (id) => form.accounts.firstWhere((a) => a.id == id).name, label: "Account", error: form.accountError, (picked) {
          form.setAccount(picked);
        }),
        if (form.needsCategory) ...[
          Picker(form.categoryId, form.categories.map((c) => c.id).toList(), labelOf: (id) => form.categories.firstWhere((c) => c.id == id).name, label: "Category", error: form.categoryError, (picked) {
            form.setCategory(picked);
          }),
        ],
        DateField(form.date, label: "Date", (picked) {
          form.setDate(picked);
        }),
        Field(controller: note, label: "Note", hint: "What was it for?", maxLines: 2),
        Button(form.isSaving ? "Saving…": "Save", () {
          form.save(amountText: amount.text, note: note.text).then((saved) {
          if (saved) nav.pop();
          });
        }),
        if (form.isEditing) ...[
          Button("Delete", () {
            form.delete().then((_) => nav.pop());
          }),
        ],
      ],
    );
  }
}

@page('/transactions/new')
class NewTransactionScreen extends Composable {
  const NewTransactionScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: TransactionForm(id: ""),
    );
  }
}

@page('/transactions/:id')
class EditTransactionScreen extends Composable {
  const EditTransactionScreen({required this.id, super.key});

  final String id;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: TransactionForm(id: id),
    );
  }
}
