// GENERATED by flxc from transactions.flx.
// Do not edit by hand — your changes will be overwritten.
// ignore_for_file: unused_import, prefer_const_constructors,
// ignore_for_file: unnecessary_brace_in_string_interps,
// ignore_for_file: prefer_single_quotes, directives_ordering,
// ignore_for_file: lines_longer_than_80_chars,
// ignore_for_file: require_trailing_commas,
// ignore_for_file: prefer_const_literals_to_create_immutables

import 'package:flutter/material.dart';

import 'package:flx_runtime/flx_runtime.dart';
import '../data/transactions_view_models.dart';
import '../domain/models.dart';

class TransactionRow extends Composable {
  const TransactionRow({required this.vm, required this.tx, super.key});

  final TransactionsViewModel vm;
  final Transaction tx;

  @override
  Widget build(BuildContext context) {
    final nav = useNavigator();

    return Tile(title: tx.note.isEmpty ? vm.categoryName(tx) : tx.note, subtitle: "${vm.categoryName(tx)} · ${vm.accountName(tx)} · ${formatRelativeDate(tx.date)}", trailing: tx.kind == TxKind.income ? tx.amount.format(showSign: true) : "-${tx.amount.format()}", leading: Dot(Color(vm.categoryColor(tx))), onTap: () => nav.toPath("/transactions/${tx.id}"));
  }
}

@page('/transactions')
class TransactionsScreen extends Composable {
  const TransactionsScreen({super.key});

  @override
  Widget build(BuildContext context) {
    final vm = useViewModel<TransactionsViewModel>();
    final nav = useNavigator();
    final search = useTextField(text: vm.query.search);

    return Screen(
      title: "Transactions",
      subtitle: vm.countLabel,
      fabIcon: Icons.add,
      onFab: () => nav.toPath("/transactions/new"),
      children: [
        SearchField(search, hint: "Search notes, categories, amounts", (text) {
          vm.setSearch(text);
        }),
        [
          Button(vm.query.kind == null ? "All" : vm.query.kind!.label, () {
            vm.setKind(vm.query.kind == null ? TxKind.expense : null);
          }),
          if (vm.isFiltered) ...[
            Button("Clear filters", () {
              vm.clearFilters();
            }),
          ],
        ].row(gap: 8),
        LazyColumn(items: vm.items, gap: 4, onEndReached: vm.loadMore, empty: EmptyState(title: "Nothing found", subtitle: "Try a different search or clear the filters"), itemBuilder: (tx, _) => TransactionRow(vm: vm, tx: tx)).expanded(),
        if (vm.hasMore) ...[
          Text("Keep scrolling to load more", style: Styles.caption),
        ],
      ],
    );
  }
}
