// GENERATED by flxc from profile.flx — do not edit by hand.
import 'package:flutter/material.dart';

import '../clean_ui/clean_ui.dart';
import '../data/user_repository.dart';
import 'settings.dart';

@page('/profile')
class ProfileScreen extends Composable {
  const ProfileScreen({super.key});

  @override
  Widget build(BuildContext context) {
    final user$ = useFetch(api.currentUser);
    final count = useState(0);
    final nav = useNavigator();

    return Scaffold(
      body: user$.when(
      loading: () => const Center(child: CircularProgressIndicator()),
      error: (error) => Center(child: Text('Error: $error')),
      data: (user) {
        return [
        Avatar(user.photo, size: 64),
        Text(user.name, style: Styles.title),
        Text("Taps: ${count.value}"),
        Button("Tap me", () {
          count.value++;
        }),
        Button("Settings", () {
          nav.to(SettingsScreen());
        }),
        Button("Open user 42", () {
          nav.toPath("/user/42");
        }),
        Button("Todos", () {
          nav.toPath("/todos");
        }),
      ].column(gap: 12, main: MainAxisAlignment.center).padding(16);
      },
    ),
    );
  }
}
