// GENERATED by flxc from settings.flx — do not edit by hand.
import 'package:flutter/material.dart';

import '../clean_ui/clean_ui.dart';

@page('/settings')
class SettingsScreen extends Composable {
  const SettingsScreen({super.key});

  @override
  Widget build(BuildContext context) {
    final scheme = useColorScheme();
    final size = useScreenSize();
    final nav = useNavigator();
    final dark = useState(false);

    return Scaffold(
      body: [
        Text("Settings", style: Styles.title),
        Text("Screen: ${size.width.toInt()} x ${size.height.toInt()}"),
        Text("Primary: ${scheme.primary}", style: Styles.caption),
        Text("Dark mode: ${dark.value}"),
        Button("Toggle dark mode", () {
          dark.value = !dark.value;
        }),
        Button("Back", () {
          nav.pop();
        }),
      ].column(gap: 12, main: MainAxisAlignment.center).padding(16),
    );
  }
}
