// GENERATED by flxc from todos.flx — do not edit by hand.
import 'package:flutter/material.dart';

import '../clean_ui/clean_ui.dart';

@page('/todos')
class TodosScreen extends Composable {
  const TodosScreen({super.key});

  @override
  Widget build(BuildContext context) {
    final nav = useNavigator();
    final todos = useState(["Learn flx", "Ship the transpiler", "Publish to pub.dev"]);
    final showTip = useState(true);

    return Scaffold(
      body: [
        Text("Todos", style: Styles.title),
        if (showTip.value) ...[
          Text("This line is rendered by DSL if/else", style: Styles.caption),
        ] else ...[
          Text("Tip hidden — else branch works too", style: Styles.caption),
        ],
        for (final todo in todos.value) ...[
          Text("• ${todo}"),
        ],
        Button("Toggle tip", () {
          showTip.value = !showTip.value;
        }),
        Button("Back", () {
          nav.pop();
        }),
      ].column(gap: 12, main: MainAxisAlignment.center).padding(16),
    );
  }
}
