// GENERATED by flxc from user.flx — do not edit by hand.
import 'package:flutter/material.dart';

import '../clean_ui/clean_ui.dart';

@page('/user/:id')
class UserScreen extends Composable {
  const UserScreen({required this.id, super.key});
  final String id;

  @override
  Widget build(BuildContext context) {
    final nav = useNavigator();

    return Scaffold(
      body: [
        Text("User profile", style: Styles.title),
        Text("User id: ${id}"),
        Text("Opened via route /user/${id}", style: Styles.caption),
        Button("Back", () {
          nav.pop();
        }),
      ].column(gap: 12, main: MainAxisAlignment.center).padding(16),
    );
  }
}
