import 'ast.dart';
import 'diagnostics.dart';
import 'parser.dart'
    show baseNameOf, containerWidgets, layoutWidgets, scaffoldProviders;

/// Named arguments that are lifted out of a layout call and applied as a
/// trailing modifier chain instead. `Column(padding: 16) { ... }` becomes
/// `[...].column().padding(16)`.
enum _Mod { value, flag }

const _modifiers = <String, _Mod>{
  'padding': _Mod.value,
  'paddingSymmetric': _Mod.value,
  'background': _Mod.value,
  'rounded': _Mod.value,
  'opacity': _Mod.value,
  'center': _Mod.flag,
  'safeArea': _Mod.flag,
  'scrollable': _Mod.flag,
  'expanded': _Mod.flag,
  'card': _Mod.flag,
};

/// The subset safe to lift onto a widget flxc knows nothing about.
///
/// Modifiers are extension methods on Widget, and in Dart an instance member
/// always beats an extension method. So lifting `scrollable: true` onto a
/// widget that happens to declare a `scrollable` field silently resolves to
/// that field and fails with "the expression doesn't evaluate to a function"
/// — pointing at the constructor, nowhere near the real cause.
///
/// `padding`, `scrollable` and `gap` are the names container-style widgets
/// most often declare themselves, so they are only lifted for layout widgets,
/// where the target is a List<Widget> extension that cannot collide.
const _universalModifiers = <String>{
  'expanded',
  'center',
  'card',
  'rounded',
  'opacity',
  'background',
  'safeArea',
  'paddingSymmetric',
};

/// `style: .title` → `Styles.title`. The DSL elides the type name; codegen
/// restores it from the argument name.
const _shorthandTypes = <String, String>{
  'style': 'Styles',
  'main': 'MainAxisAlignment',
  'cross': 'CrossAxisAlignment',
  'alignment': 'Alignment',
  'textAlign': 'TextAlign',
  'overflow': 'TextOverflow',
  'fit': 'BoxFit',
  'axis': 'Axis',
  'keyboard': 'TextInputType',
};

/// Argument-name suffixes that imply a type, so every `*Icon` parameter
/// resolves `.add` to `Icons.add` without being listed one by one.
const _shorthandSuffixes = <String, String>{
  'Icon': 'Icons',
  'Color': 'Colors',
  'Alignment': 'Alignment',
};

/// `size:` means MainAxisSize on a layout, but is a plain argument anywhere
/// else, so it is resolved per-widget rather than globally.
const _layoutOnlyShorthands = <String, String>{'size': 'MainAxisSize'};

const _indent = '  ';

/// Emits Dart source for a parsed `.flx` file.
class CodeGenerator {
  CodeGenerator(this.file, {required this.runtimeImport});

  final FlxFile file;

  /// Import used for the flx runtime, e.g. `package:flx/flx.dart`.
  final String runtimeImport;

  String generate() {
    final buf = StringBuffer()
      ..writeln('// GENERATED by flxc from ${_basename(file.source.path)}.')
      ..writeln('// Do not edit by hand — your changes will be overwritten.')
      // Generated code is judged by the .flx it came from, not by lint rules
      // aimed at hand-written Dart.
      ..writeln('// ignore_for_file: unused_import, prefer_const_constructors,')
      ..writeln('// ignore_for_file: unnecessary_brace_in_string_interps,')
      ..writeln('// ignore_for_file: prefer_single_quotes, directives_ordering,')
      ..writeln('// ignore_for_file: lines_longer_than_80_chars,')
      ..writeln('// ignore_for_file: require_trailing_commas,')
      ..writeln('// ignore_for_file: prefer_const_literals_to_create_immutables')
      ..writeln()
      ..writeln("import 'package:flutter/material.dart';")
      ..writeln()
      ..writeln("import '$runtimeImport';");
    for (final imp in file.imports) {
      buf.writeln('import ${imp.dartDirective};');
    }

    for (final declaration in file.declarations) {
      buf
        ..writeln()
        ..writeln(declaration);
    }

    for (final c in file.composables) {
      buf
        ..writeln()
        ..write(_composable(c));
    }
    return buf.toString();
  }

  /// A `useFetch` val is emitted as `name$`, and the unwrapped `name` only
  /// exists inside the `.when(data:)` closure that wraps the widget tree.
  /// A later val therefore cannot see it — and because hooks are positional,
  /// moving the val into that closure would make it run conditionally and
  /// corrupt the slot order. So this is a compile error, not a codegen trick.
  void _checkValOrder(ComposableDecl c) {
    final resolvedLater = <String>[];
    for (final v in c.vals) {
      for (final pending in resolvedLater) {
        if (v.references.contains(pending)) {
          throw FlxError(
            "val '${v.name}' uses '$pending' before it has loaded",
            v.span,
            hint: "'$pending' only exists inside the widget tree, after the "
                "fetch resolves. Up here, use the AsyncValue itself — "
                "'$pending\$.data' — or refetch with "
                "keys: [$pending\$.data].",
          );
        }
      }
      if (v.isAsync) resolvedLater.add(v.name);
    }
  }

  String _composable(ComposableDecl c) {
    _checkValOrder(c);
    final buf = StringBuffer();

    if (c.isPage) buf.writeln("@page('${c.route}')");
    buf.writeln('class ${c.name}${c.typeParams} extends Composable {');

    // Constructor
    if (c.params.isEmpty) {
      buf.writeln('${_indent}const ${c.name}({super.key});');
    } else {
      final ctorParams = c.params.map((p) {
        if (p.defaultValue != null) {
          return 'this.${p.name} = ${p.defaultValue}';
        }
        return 'required this.${p.name}';
      }).join(', ');
      buf.writeln('${_indent}const ${c.name}({$ctorParams, super.key});');
      buf.writeln();
      for (final p in c.params) {
        buf.writeln('${_indent}final ${p.type} ${p.name};');
      }
    }

    buf
      ..writeln()
      ..writeln('$_indent@override')
      ..writeln('${_indent}Widget build(BuildContext context) {');

    final asyncVals = <ValDecl>[];
    for (final v in c.vals) {
      if (v.isAsync) {
        asyncVals.add(v);
        // The AsyncValue itself lives in `name$`; `name` is the unwrapped
        // value bound by the `.when(data:)` closure below.
        buf.writeln('${_pad(2)}final ${v.name}\$ = ${v.expr};');
      } else {
        final declared = v.type == null ? 'final' : 'final ${v.type}';
        buf.writeln('${_pad(2)}$declared ${v.name} = ${v.expr};');
      }
    }
    for (final statement in c.statements) {
      buf.writeln('${_pad(2)}$statement');
    }
    if (c.vals.isNotEmpty || c.statements.isNotEmpty) buf.writeln();

    // A root that already provides a Scaffold (Screen, or a hand-written
    // Scaffold) must not get a second one wrapped around it.
    final root = c.root;
    final providesScaffold =
        root is WidgetNode && scaffoldProviders.contains(baseNameOf(root.name));
    final wrapInScaffold = c.isPage && !providesScaffold;

    // Work out where the root expression will sit before generating it: the
    // Scaffold adds one level for `body:`, and every async val adds two more
    // for its `.when(data: (x) { return ... })` closure.
    final baseDepth = wrapInScaffold ? 3 : 2;
    final rootDepth = baseDepth + 2 * asyncVals.length;

    var expr = _node(c.root, rootDepth);

    // Wrap in .when() for each async val, innermost first.
    for (var i = asyncVals.length - 1; i >= 0; i--) {
      expr = _asyncWrap(asyncVals[i].name, expr, baseDepth + 2 * i);
    }
    if (wrapInScaffold) {
      expr = 'Scaffold(\n'
          '${_pad(3)}body: $expr,\n'
          '${_pad(2)})';
    }

    buf
      ..writeln('${_pad(2)}return $expr;')
      ..writeln('$_indent}')
      ..writeln('}');
    return buf.toString();
  }

  String _asyncWrap(String name, String inner, int depth) {
    final p = _pad(depth);
    return '$name\$.when(\n'
        '$p${_indent}loading: () => const Center(child: CircularProgressIndicator()),\n'
        "$p${_indent}error: (error) => Center(child: Text('Error: \$error')),\n"
        '$p${_indent}data: ($name) {\n'
        '$p$_indent${_indent}return $inner;\n'
        '$p$_indent},\n'
        '$p)';
  }

  // ------------------------------------------------------------------ nodes

  /// Renders a node as an expression. [depth] is the indent level of the line
  /// the expression starts on.
  String _node(Node node, int depth) => switch (node) {
        WidgetNode() => _widget(node, depth),
        IfNode() => throw FlxError(
            '`if` cannot be the root of a composable',
            node.span,
            hint: 'a widget must always be returned — wrap it in a Column '
                '{ ... }, or use a ternary in an argument',
          ),
        ForNode() => throw FlxError(
            '`for` cannot be the root of a composable',
            node.span,
            hint: 'wrap it in a Column { ... } so there is a single root '
                'widget',
          ),
        RawNode() => node.isSpread
            ? throw FlxError(
                '`...` cannot be the root of a composable',
                node.span,
                hint: 'a composable returns one widget — wrap it in a '
                    'Column { ... }',
              )
            : node.expression,
      };

  String _widget(WidgetNode w, int depth) {
    // A bare name refers to a widget that already exists; calling it would
    // be wrong.
    if (w.isReference) return w.name;

    final base = baseNameOf(w.name);
    if (layoutWidgets.containsKey(base)) return _layout(w, depth);
    if (containerWidgets.contains(base)) return _container(w, depth);

    final split = _splitArgs(w, depth);
    final args = split.args;

    if (w.isBuilder) {
      args.add(_itemBuilder(w, depth));
    } else if (w.callback != null) {
      args.add(_callback(w.callback!, w.callbackParams, depth));
    }

    // An argument holding a widget tree spans several lines, and packing the
    // rest onto the same line makes the result unreadable. Generated code is
    // meant to be read, so wrap.
    final prefix = w.isConst ? 'const ' : '';
    if (_hasNestedTree(w)) {
      return '$prefix${w.name}(\n'
          '${_pad(depth + 1)}${args.join(',\n${_pad(depth + 1)}')},\n'
          '${_pad(depth)})${split.modifiers.join()}';
    }
    return '$prefix${w.name}(${args.join(', ')})${split.modifiers.join()}';
  }

  /// True when any argument contains a widget tree or a widget-returning
  /// block, and therefore renders across multiple lines.
  static bool _hasNestedTree(WidgetNode w) {
    for (final a in w.args) {
      for (final part in a.parts) {
        if (part is WidgetPart) return true;
        if (part is LambdaPart && part.returnsWidget) {
          if (part.children!.length > 1) return true;
          if (part.children!.first is! WidgetNode) return true;
          if (_hasNestedTree(part.children!.first as WidgetNode)) return true;
          final only = part.children!.first as WidgetNode;
          if (only.children != null) return true;
        }
      }
    }
    return false;
  }

  /// Separates real constructor arguments from modifier-chain arguments.
  ///
  /// `expanded: true` becomes `.expanded()` on any widget, so a lazy list can
  /// fill the space inside a Screen. Layout widgets get the full modifier set
  /// because their target is a `List<Widget>` extension with no members to
  /// collide with; every other widget gets only [_universalModifiers].
  ({List<String> args, List<String> modifiers}) _splitArgs(
    WidgetNode w,
    int depth,
  ) {
    final isLayout = layoutWidgets.containsKey(baseNameOf(w.name));

    final args = <String>[];
    final modifiers = <String>[];

    for (final a in w.args) {
      final name = a.name;
      final liftable =
          name != null && (isLayout || _universalModifiers.contains(name));
      final mod = liftable ? _modifiers[name] : null;

      if (mod == null) {
        final value = _argValue(a, w.name, depth);
        args.add(name == null ? value : '$name: $value');
        continue;
      }

      if (mod == _Mod.flag) {
        if (a.text == 'false') continue;
        if (a.text != 'true') {
          throw FlxError(
            "'$name:' on ${w.name} is a flag and only accepts true or false",
            a.span,
            hint: 'write  $name: true',
          );
        }
        modifiers.add('.$name()');
      } else {
        modifiers.add('.$name(${_argValue(a, w.name, depth)})');
      }
    }
    return (args: args, modifiers: modifiers);
  }

  /// `Screen(title: "Inbox") { a, b }` → `Screen(title: "Inbox", children: [a, b])`
  String _container(WidgetNode w, int depth) {
    final split = _splitArgs(w, depth);
    final args = split.args;

    final children = w.children ?? const <Node>[];
    args.add('children: [\n'
        '${children.map((c) => _child(c, depth + 2)).join(',\n')},\n'
        '${_pad(depth + 1)}]');

    return '${w.name}(\n'
        '${_pad(depth + 1)}${args.join(',\n${_pad(depth + 1)}')},\n'
        '${_pad(depth)})${split.modifiers.join()}';
  }

  /// `LazyColumn(items: xs) { x in Row { ... } }`
  ///   → `LazyColumn(items: xs, itemBuilder: (x, _) => [...].row())`
  ///
  /// The second parameter is always emitted so the runtime has a single
  /// signature; `_` when the DSL did not ask for the index.
  String _itemBuilder(WidgetNode w, int depth) {
    final children = w.children ?? const <Node>[];
    final index = w.indexVariable ?? '_';

    // A single child is the common case and reads better inline; several
    // children are stacked into a column so the block stays unrestricted.
    final body = children.length == 1 && children.first is WidgetNode
        ? _widget(children.first as WidgetNode, depth + 1)
        : '[\n'
            '${children.map((c) => _child(c, depth + 2)).join(',\n')},\n'
            '${_pad(depth + 1)}].column()';

    return 'itemBuilder: (${w.itemVariable}, $index) => $body';
  }

  /// `Column(gap: 12, padding: 16) { a, b }`
  ///   → `[a, b].column(gap: 12).padding(16)`
  String _layout(WidgetNode w, int depth) {
    final method = layoutWidgets[baseNameOf(w.name)]!;

    for (final a in w.args) {
      if (a.name == null) {
        throw FlxError(
          'positional arguments are not supported on ${w.name}',
          a.span,
          hint: 'use named arguments, e.g. ${w.name}(gap: 12)',
        );
      }
    }

    final split = _splitArgs(w, depth);
    final callArgs = split.args;
    final mods = split.modifiers;

    final children = w.children ?? const <Node>[];
    final inner = children.isEmpty
        ? '[]'
        : '[\n'
            '${children.map((c) => _child(c, depth + 1)).join(',\n')},\n'
            '${_pad(depth)}]';

    return '$inner.$method(${callArgs.join(', ')})${mods.join()}';
  }

  /// Renders a child of a layout block. Unlike [_node], `if` and `for` are
  /// legal here — they become Dart's collection-if and collection-for.
  String _child(Node node, int depth) {
    final pad = _pad(depth);
    return switch (node) {
      WidgetNode() => '$pad${_widget(node, depth)}',
      IfNode() => '$pad${_collectionIf(node, depth)}',
      ForNode() => '$pad${_collectionFor(node, depth)}',
      // `...items` becomes a collection spread; `(expr)` is passed straight
      // through as the widget it evaluates to.
      RawNode() => node.isSpread
          ? '$pad${node.spreadOperator}${node.expression}'
          : '$pad${node.expression}',
    };
  }

  /// A branch may hold several widgets, so every branch spreads a list.
  /// That keeps `if` usable anywhere a child is, with no arity rules.
  String _collectionIf(IfNode node, int depth) {
    final pad = _pad(depth);
    final buf = StringBuffer('if (${node.condition}) ...[\n')
      ..write(node.then.map((c) => _child(c, depth + 1)).join(',\n'))
      ..write(',\n$pad]');

    final orElse = node.orElse;
    if (orElse != null) {
      if (orElse.length == 1 && orElse.first is IfNode) {
        buf.write(' else ${_collectionIf(orElse.first as IfNode, depth)}');
      } else {
        buf
          ..write(' else ...[\n')
          ..write(orElse.map((c) => _child(c, depth + 1)).join(',\n'))
          ..write(',\n$pad]');
      }
    }
    return buf.toString();
  }

  String _collectionFor(ForNode node, int depth) {
    final pad = _pad(depth);
    return 'for (final ${node.variable} in ${node.iterable}) ...[\n'
        '${node.children.map((c) => _child(c, depth + 1)).join(',\n')},\n'
        '$pad]';
  }

  /// Renders an argument value: plain Dart, a widget tree, a block lambda, or
  /// any mix of the three.
  String _argValue(Arg a, String widget, int depth) {
    if (a.text != null) return _shorthand(a, widget);

    final buffer = StringBuffer();
    for (final part in a.parts) {
      switch (part) {
        case DartText():
          buffer.write(part.text);
        case WidgetPart():
          buffer.write(_widget(part.widget, depth + 1));
        case LambdaPart():
          buffer.write(_lambda(part, depth));
      }
    }
    return buffer.toString();
  }

  /// `{ a, b => Widget }` → `(a, b) => Widget`
  /// `{ a -> stmts }`     → `(a) { stmts; }`
  String _lambda(LambdaPart lambda, int depth) {
    final signature = '(${lambda.params.join(', ')})';

    final children = lambda.children;
    if (children == null) {
      return _callback(lambda.statements ?? '', lambda.params, depth);
    }

    // A single child reads better inline; several are stacked into a column
    // so the block stays unrestricted.
    final body = children.length == 1 && children.first is WidgetNode
        ? _widget(children.first as WidgetNode, depth + 1)
        : '[\n'
            '${children.map((c) => _child(c, depth + 2)).join(',\n')},\n'
            '${_pad(depth + 1)}].column()';

    return '$signature => $body';
  }

  String _shorthand(Arg a, String widget) {
    final value = a.text!;
    if (!a.isShorthand) return value;
    final name = a.name;
    if (name == null) return value;

    final type = _shorthandTypes[name] ??
        _suffixType(name) ??
        (layoutWidgets.containsKey(baseNameOf(widget))
            ? _layoutOnlyShorthands[name]
            : null);
    if (type == null) {
      throw FlxError(
        "'$name: $value' — flxc doesn't know what type '$value' belongs to",
        a.span,
        hint: 'write the type out in full, e.g. $name: SomeType$value',
      );
    }
    return '$type$value';
  }

  /// Callback bodies are raw Dart. Re-indent them to sit correctly in the
  /// generated file and add the semicolons the DSL lets you omit.
  String _callback(String raw, List<String> params, int depth) {
    // A body that awaits has to be async. Requiring the author to say so
    // twice would be noise, and forgetting it produces a Dart error inside
    // generated code.
    final isAsync = RegExp(r'(?<![\w$])await(?![\w$])').hasMatch(raw);
    final signature = '(${params.join(', ')})${isAsync ? ' async' : ''}';
    final pad = _pad(depth + 1);
    final lines = raw
        .split('\n')
        .map((l) => l.trim())
        .where((l) => l.isNotEmpty)
        .map((l) {
      final needsSemicolon = !l.endsWith(';') &&
          !l.endsWith('{') &&
          !l.endsWith('}') &&
          !l.endsWith(',');
      return '$pad$l${needsSemicolon ? ';' : ''}';
    }).toList();

    if (lines.isEmpty) return '$signature {}';
    return '$signature {\n${lines.join('\n')}\n${_pad(depth)}}';
  }

  /// `fabIcon` → Icons, `accentColor` → Colors. Matched case-sensitively on
  /// the suffix so `iconSize` (a double) is not caught by mistake.
  static String? _suffixType(String name) {
    for (final entry in _shorthandSuffixes.entries) {
      if (name == entry.key.toLowerCase() ||
          (name.length > entry.key.length && name.endsWith(entry.key))) {
        return entry.value;
      }
    }
    return null;
  }

  static String _pad(int depth) => _indent * depth;

  static String _basename(String path) =>
      path.split(RegExp(r'[/\\]')).last;
}
