import 'ast.dart';
import 'diagnostics.dart';
import 'parser.dart' show layoutWidgets;

/// Named arguments that are lifted out of a layout call and applied as a
/// trailing modifier chain instead. `Column(padding: 16) { ... }` becomes
/// `[...].column().padding(16)`.
enum _Mod { value, flag }

const _modifiers = <String, _Mod>{
  'padding': _Mod.value,
  'paddingSymmetric': _Mod.value,
  'background': _Mod.value,
  'rounded': _Mod.value,
  'opacity': _Mod.value,
  'center': _Mod.flag,
  'safeArea': _Mod.flag,
  'scrollable': _Mod.flag,
  'expanded': _Mod.flag,
  'card': _Mod.flag,
};

/// `style: .title` → `Styles.title`. The DSL elides the type name; codegen
/// restores it from the argument name.
const _shorthandTypes = <String, String>{
  'style': 'Styles',
  'main': 'MainAxisAlignment',
  'cross': 'CrossAxisAlignment',
  'alignment': 'Alignment',
  'textAlign': 'TextAlign',
  'overflow': 'TextOverflow',
  'fit': 'BoxFit',
  'axis': 'Axis',
};

/// `size:` means MainAxisSize on a layout, but is a plain argument anywhere
/// else, so it is resolved per-widget rather than globally.
const _layoutOnlyShorthands = <String, String>{'size': 'MainAxisSize'};

const _indent = '  ';

/// Emits Dart source for a parsed `.flx` file.
class CodeGenerator {
  CodeGenerator(this.file, {required this.runtimeImport});

  final FlxFile file;

  /// Import used for the flx runtime, e.g. `package:flx/flx.dart`.
  final String runtimeImport;

  String generate() {
    final buf = StringBuffer()
      ..writeln('// GENERATED by flxc from ${_basename(file.source.path)}.')
      ..writeln('// Do not edit by hand — your changes will be overwritten.')
      // Generated code is judged by the .flx it came from, not by lint rules
      // aimed at hand-written Dart.
      ..writeln('// ignore_for_file: unused_import, prefer_const_constructors,')
      ..writeln('// ignore_for_file: unnecessary_brace_in_string_interps,')
      ..writeln('// ignore_for_file: prefer_single_quotes, directives_ordering,')
      ..writeln('// ignore_for_file: lines_longer_than_80_chars,')
      ..writeln('// ignore_for_file: require_trailing_commas,')
      ..writeln('// ignore_for_file: prefer_const_literals_to_create_immutables')
      ..writeln()
      ..writeln("import 'package:flutter/material.dart';")
      ..writeln()
      ..writeln("import '$runtimeImport';");
    for (final imp in file.imports) {
      buf.writeln('import ${imp.dartLiteral};');
    }

    for (final c in file.composables) {
      buf
        ..writeln()
        ..write(_composable(c));
    }
    return buf.toString();
  }

  /// A `useFetch` val is emitted as `name$`, and the unwrapped `name` only
  /// exists inside the `.when(data:)` closure that wraps the widget tree.
  /// A later val therefore cannot see it — and because hooks are positional,
  /// moving the val into that closure would make it run conditionally and
  /// corrupt the slot order. So this is a compile error, not a codegen trick.
  void _checkValOrder(ComposableDecl c) {
    final resolvedLater = <String>[];
    for (final v in c.vals) {
      for (final pending in resolvedLater) {
        if (v.references.contains(pending)) {
          throw FlxError(
            "val '${v.name}' uses '$pending' before it has loaded",
            v.span,
            hint: "'$pending' only exists inside the widget tree, after the "
                "fetch resolves. Up here, use the AsyncValue itself — "
                "'$pending\$.data' — or refetch with "
                "keys: [$pending\$.data].",
          );
        }
      }
      if (v.isAsync) resolvedLater.add(v.name);
    }
  }

  String _composable(ComposableDecl c) {
    _checkValOrder(c);
    final buf = StringBuffer();

    if (c.isPage) buf.writeln("@page('${c.route}')");
    buf.writeln('class ${c.name} extends Composable {');

    // Constructor
    if (c.params.isEmpty) {
      buf.writeln('${_indent}const ${c.name}({super.key});');
    } else {
      final ctorParams = c.params.map((p) {
        if (p.defaultValue != null) {
          return 'this.${p.name} = ${p.defaultValue}';
        }
        return 'required this.${p.name}';
      }).join(', ');
      buf.writeln('${_indent}const ${c.name}({$ctorParams, super.key});');
      buf.writeln();
      for (final p in c.params) {
        buf.writeln('${_indent}final ${p.type} ${p.name};');
      }
    }

    buf
      ..writeln()
      ..writeln('$_indent@override')
      ..writeln('${_indent}Widget build(BuildContext context) {');

    final asyncVals = <ValDecl>[];
    for (final v in c.vals) {
      if (v.isAsync) {
        asyncVals.add(v);
        // The AsyncValue itself lives in `name$`; `name` is the unwrapped
        // value bound by the `.when(data:)` closure below.
        buf.writeln('${_pad(2)}final ${v.name}\$ = ${v.expr};');
      } else {
        buf.writeln('${_pad(2)}final ${v.name} = ${v.expr};');
      }
    }
    if (c.vals.isNotEmpty) buf.writeln();

    // Work out where the root expression will sit before generating it: a
    // page adds one level for `body:`, and every async val adds two more for
    // its `.when(data: (x) { return ... })` closure.
    final baseDepth = c.isPage ? 3 : 2;
    final rootDepth = baseDepth + 2 * asyncVals.length;

    var expr = _node(c.root, rootDepth);

    // Wrap in .when() for each async val, innermost first.
    for (var i = asyncVals.length - 1; i >= 0; i--) {
      expr = _asyncWrap(asyncVals[i].name, expr, baseDepth + 2 * i);
    }
    if (c.isPage) {
      expr = 'Scaffold(\n'
          '${_pad(3)}body: $expr,\n'
          '${_pad(2)})';
    }

    buf
      ..writeln('${_pad(2)}return $expr;')
      ..writeln('$_indent}')
      ..writeln('}');
    return buf.toString();
  }

  String _asyncWrap(String name, String inner, int depth) {
    final p = _pad(depth);
    return '$name\$.when(\n'
        '$p${_indent}loading: () => const Center(child: CircularProgressIndicator()),\n'
        "$p${_indent}error: (error) => Center(child: Text('Error: \$error')),\n"
        '$p${_indent}data: ($name) {\n'
        '$p$_indent${_indent}return $inner;\n'
        '$p$_indent},\n'
        '$p)';
  }

  // ------------------------------------------------------------------ nodes

  /// Renders a node as an expression. [depth] is the indent level of the line
  /// the expression starts on.
  String _node(Node node, int depth) => switch (node) {
        WidgetNode() => _widget(node, depth),
        IfNode() => throw FlxError(
            '`if` cannot be the root of a composable',
            node.span,
            hint: 'a widget must always be returned — wrap it in a Column '
                '{ ... }, or use a ternary in an argument',
          ),
        ForNode() => throw FlxError(
            '`for` cannot be the root of a composable',
            node.span,
            hint: 'wrap it in a Column { ... } so there is a single root '
                'widget',
          ),
      };

  String _widget(WidgetNode w, int depth) {
    if (layoutWidgets.containsKey(w.name)) return _layout(w, depth);

    final args = <String>[];
    for (final a in w.args) {
      args.add(a.name == null
          ? _shorthand(a, w.name)
          : '${a.name}: ${_shorthand(a, w.name)}');
    }
    if (w.callback != null) {
      args.add(_callback(w.callback!, depth));
    }
    return '${w.name}(${args.join(', ')})';
  }

  /// `Column(gap: 12, padding: 16) { a, b }`
  ///   → `[a, b].column(gap: 12).padding(16)`
  String _layout(WidgetNode w, int depth) {
    final method = layoutWidgets[w.name]!;
    final callArgs = <String>[];
    final mods = <String>[];

    for (final a in w.args) {
      final name = a.name;
      if (name == null) {
        throw FlxError(
          'positional arguments are not supported on ${w.name}',
          a.span,
          hint: 'use named arguments, e.g. ${w.name}(gap: 12)',
        );
      }
      final mod = _modifiers[name];
      if (mod == null) {
        callArgs.add('$name: ${_shorthand(a, w.name)}');
        continue;
      }
      if (mod == _Mod.flag) {
        // `center: true` → `.center()`; `center: false` → nothing.
        if (a.value == 'false') continue;
        if (a.value != 'true') {
          throw FlxError(
            "'$name:' on ${w.name} is a flag and only accepts true or false",
            a.span,
            hint: 'write  $name: true',
          );
        }
        mods.add('.$name()');
      } else {
        mods.add('.$name(${_shorthand(a, w.name)})');
      }
    }

    final children = w.children ?? const <Node>[];
    final inner = children.isEmpty
        ? '[]'
        : '[\n'
            '${children.map((c) => _child(c, depth + 1)).join(',\n')},\n'
            '${_pad(depth)}]';

    return '$inner.$method(${callArgs.join(', ')})${mods.join()}';
  }

  /// Renders a child of a layout block. Unlike [_node], `if` and `for` are
  /// legal here — they become Dart's collection-if and collection-for.
  String _child(Node node, int depth) {
    final pad = _pad(depth);
    return switch (node) {
      WidgetNode() => '$pad${_widget(node, depth)}',
      IfNode() => '$pad${_collectionIf(node, depth)}',
      ForNode() => '$pad${_collectionFor(node, depth)}',
    };
  }

  /// A branch may hold several widgets, so every branch spreads a list.
  /// That keeps `if` usable anywhere a child is, with no arity rules.
  String _collectionIf(IfNode node, int depth) {
    final pad = _pad(depth);
    final buf = StringBuffer('if (${node.condition}) ...[\n')
      ..write(node.then.map((c) => _child(c, depth + 1)).join(',\n'))
      ..write(',\n$pad]');

    final orElse = node.orElse;
    if (orElse != null) {
      if (orElse.length == 1 && orElse.first is IfNode) {
        buf.write(' else ${_collectionIf(orElse.first as IfNode, depth)}');
      } else {
        buf
          ..write(' else ...[\n')
          ..write(orElse.map((c) => _child(c, depth + 1)).join(',\n'))
          ..write(',\n$pad]');
      }
    }
    return buf.toString();
  }

  String _collectionFor(ForNode node, int depth) {
    final pad = _pad(depth);
    return 'for (final ${node.variable} in ${node.iterable}) ...[\n'
        '${node.children.map((c) => _child(c, depth + 1)).join(',\n')},\n'
        '$pad]';
  }

  String _shorthand(Arg a, String widget) {
    if (!a.isShorthand) return a.value;
    final name = a.name;
    if (name == null) return a.value;

    final type = _shorthandTypes[name] ??
        (layoutWidgets.containsKey(widget) ? _layoutOnlyShorthands[name] : null);
    if (type == null) {
      throw FlxError(
        "'$name: ${a.value}' — flxc doesn't know what type '${a.value}' "
        'belongs to',
        a.span,
        hint: 'write the type out in full, e.g. '
            "$name: SomeType${a.value}",
      );
    }
    return '$type${a.value}';
  }

  /// Callback bodies are raw Dart. Re-indent them to sit correctly in the
  /// generated file and add the semicolons the DSL lets you omit.
  String _callback(String raw, int depth) {
    final pad = _pad(depth + 1);
    final lines = raw
        .split('\n')
        .map((l) => l.trim())
        .where((l) => l.isNotEmpty)
        .map((l) {
      final needsSemicolon = !l.endsWith(';') &&
          !l.endsWith('{') &&
          !l.endsWith('}') &&
          !l.endsWith(',');
      return '$pad$l${needsSemicolon ? ';' : ''}';
    }).toList();

    if (lines.isEmpty) return '() {}';
    return '() {\n${lines.join('\n')}\n${_pad(depth)}}';
  }

  static String _pad(int depth) => _indent * depth;

  static String _basename(String path) =>
      path.split(RegExp(r'[/\\]')).last;
}
