import 'dart:io';

import 'ast.dart';
import 'codegen.dart';
import 'diagnostics.dart';
import 'parser.dart';
import 'source.dart';

/// Result of compiling one `.flx` file.
class CompiledFile {
  CompiledFile(this.input, this.output, this.ast, this.dart);

  final String input;
  final String output;
  final FlxFile ast;
  final String dart;

  /// Pages declared in this file, in source order.
  Iterable<ComposableDecl> get pages => ast.composables.where((c) => c.isPage);
}

/// Compiles `.flx` sources to Dart and generates the route table.
class Compiler {
  Compiler({this.runtimeImport = 'package:flx/flx.dart'});

  final String runtimeImport;

  /// Transpiles a single file in memory. Throws [FlxError] on bad input.
  String compileSource(Source source) =>
      CodeGenerator(Parser.parse(source), runtimeImport: runtimeImport)
          .generate();

  CompiledFile compileFile(String inputPath) {
    final file = File(inputPath);
    final source = Source(inputPath, file.readAsStringSync());
    final ast = Parser.parse(source);
    final dart = CodeGenerator(ast, runtimeImport: runtimeImport).generate();
    return CompiledFile(
      inputPath,
      inputPath.replaceAll(RegExp(r'\.flx$'), '.dart'),
      ast,
      dart,
    );
  }

  /// Compiles every `.flx` under [dir] (recursively) and writes the results
  /// plus `routes.g.dart`. Returns a human-readable summary.
  BuildResult build(String dir, {bool write = true}) {
    final root = Directory(dir);
    if (!root.existsSync()) {
      throw FlxError("no such directory: '$dir'", null);
    }

    final inputs = root
        .listSync(recursive: true)
        .whereType<File>()
        .map((f) => f.path.replaceAll(r'\', '/'))
        .where((p) => p.endsWith('.flx'))
        .toList()
      ..sort();

    final compiled = <CompiledFile>[];
    for (final input in inputs) {
      final result = compileFile(input);
      if (write) File(result.output).writeAsStringSync(result.dart);
      compiled.add(result);
    }

    final routesPath = '${dir.replaceAll(r'\', '/')}/routes.g.dart'
        .replaceAll('//', '/');
    final routes = _generateRoutes(compiled, dir);
    if (write) File(routesPath).writeAsStringSync(routes);

    return BuildResult(compiled, routesPath, routes);
  }

  /// Builds the route table. Duplicate routes are a hard error — otherwise
  /// one silently shadows the other at runtime, which is miserable to debug.
  String _generateRoutes(List<CompiledFile> files, String dir) {
    final entries = <({ComposableDecl page, String import})>[];
    final seen = <String, String>{};

    for (final f in files) {
      for (final page in f.pages) {
        final existing = seen[page.route!];
        if (existing != null) {
          throw FlxError(
            "duplicate route '${page.route}' declared by both "
            "$existing and ${page.name}",
            page.span,
            hint: 'each @page route must be unique',
          );
        }
        seen[page.route!] = page.name;
        entries.add((page: page, import: _relativeImport(f.output, dir)));
      }
    }
    // Most specific first. The router takes the first match, so a literal
    // segment must beat a `:param` at the same position — otherwise
    // '/transactions/:id' swallows '/transactions/new' and the new-transaction
    // screen becomes unreachable.
    entries.sort((a, b) {
      final byShape = _specificity(a.page.route!)
          .compareTo(_specificity(b.page.route!));
      return byShape != 0 ? byShape : a.page.route!.compareTo(b.page.route!);
    });

    final buf = StringBuffer()
      ..writeln('// GENERATED by flxc — the app route table.')
      ..writeln('// Do not edit by hand — your changes will be overwritten.')
      ..writeln()
      ..writeln("import '$runtimeImport';");
    for (final import in {for (final e in entries) e.import}.toList()..sort()) {
      buf.writeln("import '$import';");
    }
    buf
      ..writeln()
      ..writeln('/// Every @page composable, keyed by its route pattern.')
      ..writeln('final appRoutes = <RouteDef>[');

    for (final e in entries) {
      buf.writeln('  ${_routeDef(e.page)}');
    }
    buf
      ..writeln('];')
      ..writeln();
    return buf.toString();
  }

  /// Orders routes so literals outrank parameters, left to right.
  ///
  /// Each segment contributes a digit — 0 for a literal, 1 for a `:param` —
  /// so '/a/b' (00) sorts before '/a/:x' (01), and both before '/:y/:z' (11).
  /// Padded on the right so shorter patterns are not accidentally favoured.
  static String _specificity(String route) {
    final segments = route.split('/').where((s) => s.isNotEmpty);
    final shape = segments.map((s) => s.startsWith(':') ? '1' : '0').join();
    return shape.padRight(8, '0');
  }

  String _routeDef(ComposableDecl page) {
    final routeParams = page.routeParams.toSet();
    final args = <String>[];

    for (final p in page.params) {
      if (routeParams.contains(p.name)) {
        args.add("${p.name}: params['${p.name}'] ?? ''");
      } else if (p.defaultValue == null) {
        throw FlxError(
          "@page ${page.name} has a required parameter '${p.name}' that the "
          "route '${page.route}' cannot supply",
          p.span,
          hint: "either capture it in the route (@page(\"${page.route}/"
              ":${p.name}\")) or give it a default value "
              "(${p.name}: ${p.type} = ...)",
        );
      }
      // Params with defaults are simply omitted — the constructor fills them.
    }

    final ctor = args.isEmpty
        ? 'const ${page.name}()'
        : '${page.name}(${args.join(', ')})';
    return "RouteDef('${page.route}', (params) => $ctor),";
  }

  /// Import path for [target] as seen from `<dir>/routes.g.dart`.
  String _relativeImport(String target, String dir) {
    final normalizedDir = dir.replaceAll(r'\', '/').replaceAll(RegExp(r'/$'), '');
    final normalizedTarget = target.replaceAll(r'\', '/');
    if (normalizedTarget.startsWith('$normalizedDir/')) {
      return normalizedTarget.substring(normalizedDir.length + 1);
    }
    return normalizedTarget.split('/').last;
  }
}

class BuildResult {
  BuildResult(this.files, this.routesPath, this.routesSource);

  final List<CompiledFile> files;
  final String routesPath;
  final String routesSource;

  int get pageCount => files.fold(0, (n, f) => n + f.pages.length);
  int get composableCount =>
      files.fold(0, (n, f) => n + f.ast.composables.length);
}
