// GENERATED by flxc from interop.flx.
// Do not edit by hand — your changes will be overwritten.
// ignore_for_file: unused_import, prefer_const_constructors,
// ignore_for_file: unnecessary_brace_in_string_interps,
// ignore_for_file: prefer_single_quotes, directives_ordering,
// ignore_for_file: lines_longer_than_80_chars,
// ignore_for_file: require_trailing_commas,
// ignore_for_file: prefer_const_literals_to_create_immutables

import 'package:flutter/material.dart';

import 'package:flx/flx.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:provider/provider.dart';
import 'package:get/get.dart';
import '../state.dart';

@page('/interop')
class InteropScreen extends Composable {
  const InteropScreen({super.key});

  @override
  Widget build(BuildContext context) {
    final cubit = useInject<CounterCubit>();
    final count$ = useStream(cubit.stream, initialData: cubit.state);
    final settings = Provider.of<Settings>(useContext());
    final getx = Get.find<GetxCounter>();

    return Scaffold(
      body: count$.when(
        loading: () => const Center(child: CircularProgressIndicator()),
        error: (error) => Center(child: Text('Error: $error')),
        data: (count) {
          return [
            Text("useStream from a Cubit: ${count}"),
            BlocBuilder<CounterCubit, int>(
              bloc: cubit,
              builder: (context, state) => [
                Text("BlocBuilder: ${state}"),
              ].column(gap: 4),
            ),
            Consumer<Settings>(builder: (context, model, child) => Text("Provider Consumer: ${model.name}")),
            Obx(() => Text("GetX Obx: ${getx.count.value}")),
            Button("bump", () {
              cubit.increment();
              getx.increment();
              settings.rename("Grace");
            }),
          ].column(gap: 12).padding(16);
        },
      ),
    );
  }
}
