// GENERATED by flxc from kitchen_sink.flx.
// Do not edit by hand — your changes will be overwritten.
// ignore_for_file: unused_import, prefer_const_constructors,
// ignore_for_file: unnecessary_brace_in_string_interps,
// ignore_for_file: prefer_single_quotes, directives_ordering,
// ignore_for_file: lines_longer_than_80_chars,
// ignore_for_file: require_trailing_commas,
// ignore_for_file: prefer_const_literals_to_create_immutables

import 'package:flutter/material.dart';

import 'package:flx/flx.dart';
import 'package:flutter/services.dart' as services;

enum Mode { light, dark }

String labelOf(Mode mode) => mode == Mode.light ? "Light" : "Dark";

class Box<T> extends Composable {
  const Box({required this.item, required this.render, super.key});

  final T item;
  final String Function(T) render;

  @override
  Widget build(BuildContext context) {
    return Text(render(item));
  }
}

@page('/kitchen')
class KitchenSink extends Composable {
  const KitchenSink({super.key});

  @override
  Widget build(BuildContext context) {
    final Mode mode = Mode.light;
    final controller = useScrollController();
    final text = useTextField();
    services.HapticFeedback.selectionClick();

    return Screen(
      title: "Kitchen sink",
      scrollable: true,
      children: [
        const Text("a const child"),
        Box<Mode>(item: mode, render: labelOf),
        LayoutBuilder(builder: (context, box) => Text("width ${box.maxWidth.round()}")),
        Field(controller: text, label: "Name", onSubmitted: (String value) {
          controller.jumpTo(0);
        }),
        Button("Reload", () async {
          await Future<void>.delayed(Duration.zero);
          controller.jumpTo(0);
        }),
        switch(mode) {Mode.light => Text("light"), Mode.dark => Text("dark")},
        const SizedBox(height: 8),
      ],
    );
  }
}
