// GENERATED by flxc — the app route table.
// Do not edit by hand — your changes will be overwritten.

import 'package:flx/flx.dart';
import 'interop.dart';

/// Every @page composable, keyed by its route pattern.
final appRoutes = <RouteDef>[
  RouteDef('/interop', (params) => const InteropScreen()),
];

