// GENERATED by flxc — the app route table.
// Do not edit by hand — your changes will be overwritten.

import 'package:flx/flx.dart';
import 'interop.dart';
import 'kitchen_sink.dart';
import 'ui_packages.dart';

/// Every @page composable, keyed by its route pattern.
final appRoutes = <RouteDef>[
  RouteDef('/gallery', (params) => const GalleryScreen()),
  RouteDef('/interop', (params) => const InteropScreen()),
  RouteDef('/kitchen', (params) => const KitchenSink()),
];

