// GENERATED by flxc from ui_packages.flx.
// Do not edit by hand — your changes will be overwritten.
// ignore_for_file: unused_import, prefer_const_constructors,
// ignore_for_file: unnecessary_brace_in_string_interps,
// ignore_for_file: prefer_single_quotes, directives_ordering,
// ignore_for_file: lines_longer_than_80_chars,
// ignore_for_file: require_trailing_commas,
// ignore_for_file: prefer_const_literals_to_create_immutables

import 'package:flutter/material.dart';

import 'package:flx_runtime/flx_runtime.dart';
import 'package:cached_network_image/cached_network_image.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'package:shimmer/shimmer.dart';
import 'package:flutter_staggered_grid_view/flutter_staggered_grid_view.dart';
import 'package:flutter_slidable/flutter_slidable.dart';
import 'package:fl_chart/fl_chart.dart';
import 'package:google_fonts/google_fonts.dart';

class Avatar extends Composable {
  const Avatar({required this.url, super.key});

  final String url;

  @override
  Widget build(BuildContext context) {
    return CachedNetworkImage(imageUrl: url, width: 64, height: 64, fit: BoxFit.cover, placeholder: (context, path) => Shimmer.fromColors(baseColor: Colors.grey.shade300, highlightColor: Colors.grey.shade100, child: Container(width: 64, height: 64, color: Colors.white)), errorWidget: (context, path, error) => Icon(Icons.broken_image, size: 32));
  }
}

class Header extends Composable {
  const Header({required this.title, super.key});

  final String title;

  @override
  Widget build(BuildContext context) {
    return [
      SvgPicture.asset("assets/logo.svg", width: 32, height: 32),
      Text(title, style: GoogleFonts.poppins(fontSize: 20, fontWeight: FontWeight.w600)),
    ].row(gap: 12, cross: CrossAxisAlignment.center);
  }
}

class PhotoGrid extends Composable {
  const PhotoGrid({required this.urls, super.key});

  final List<String> urls;

  @override
  Widget build(BuildContext context) {
    return MasonryGridView.count(
      crossAxisCount: 2,
      mainAxisSpacing: 8,
      crossAxisSpacing: 8,
      itemCount: urls.length,
      itemBuilder: (context, index) => [
        Avatar(url: urls[index]),
        Text("photo ${index + 1}", style: Styles.caption),
      ].column(gap: 4),
    );
  }
}

class SlidableRow extends Composable {
  const SlidableRow({required this.label, required this.onDelete, super.key});

  final String label;
  final VoidCallback onDelete;

  @override
  Widget build(BuildContext context) {
    return Slidable(endActionPane: ActionPane(motion: const DrawerMotion(), extentRatio: 0.25, children: [SlidableAction(onPressed:(context) {
      onDelete();
    }, backgroundColor: Colors.red, foregroundColor: Colors.white, icon: Icons.delete, label: "Delete",),],), child: Tile(title: label, subtitle: "swipe me"));
  }
}

class Sparkline extends Composable {
  const Sparkline({required this.points, super.key});

  final List<FlSpot> points;

  @override
  Widget build(BuildContext context) {
    return SizedBox(height: 160, child: LineChart(LineChartData(gridData: const FlGridData(show: false), titlesData: const FlTitlesData(show: false), borderData: FlBorderData(show: false), lineBarsData: [LineChartBarData(spots: points, isCurved: true, barWidth: 3, dotData: const FlDotData(show: false),),],),));
  }
}

@page('/gallery')
class GalleryScreen extends Composable {
  const GalleryScreen({super.key});

  @override
  Widget build(BuildContext context) {
    final urls = useState(["https://example.com/a.jpg", "https://example.com/b.jpg"]);
    final points = useMemoized(() =>[FlSpot(0, 1), FlSpot(1, 3), FlSpot(2, 2)]);

    return Screen(
      title: "UI packages",
      scrollable: true,
      children: [
        Header(title: "Gallery"),
        Sparkline(points: points),
        SlidableRow(label: "A slidable row", onDelete: () => urls.value =[]),
        LazyColumn(items: urls.value, gap: 8, shrinkWrap: true, itemBuilder: (url, i) => [
            Avatar(url: url),
            Text("row ${i + 1}"),
          ].row(gap: 8, cross: CrossAxisAlignment.center)),
        SizedBox(height: 320, child: PhotoGrid(urls: urls.value)),
      ],
    );
  }
}
