// GENERATED by flxc from profile.flx.
// Do not edit by hand — your changes will be overwritten.
// ignore_for_file: unused_import, prefer_const_constructors,
// ignore_for_file: unnecessary_brace_in_string_interps,
// ignore_for_file: prefer_single_quotes, directives_ordering,
// ignore_for_file: lines_longer_than_80_chars,
// ignore_for_file: require_trailing_commas,
// ignore_for_file: prefer_const_literals_to_create_immutables

import 'package:flutter/material.dart';

import 'package:flx/flx.dart';
import '../data/user_repository.dart';
import 'settings.dart';

@page('/profile')
class ProfileScreen extends Composable {
  const ProfileScreen({super.key});

  @override
  Widget build(BuildContext context) {
    final repo = useInject<UserRepository>();
    final user$ = useFetch(repo.currentUser);
    final count = useState(0);
    final nav = useNavigator();

    return Scaffold(
      body: user$.when(
        loading: () => const Center(child: CircularProgressIndicator()),
        error: (error) => Center(child: Text('Error: $error')),
        data: (user) {
          return [
            Avatar(user.photo, size: 64),
            Text(user.name, style: Styles.title),
            Text("Taps: ${count.value}"),
            Button("Tap me", () {
              count.value++;
            }),
            Button("Settings", () {
              nav.to(SettingsScreen());
            }),
            Button("Open user 42", () {
              nav.toPath("/user/42");
            }),
            Button("Todos", () {
              nav.toPath("/todos");
            }),
          ].column(gap: 12, main: MainAxisAlignment.center).padding(16);
        },
      ),
    );
  }
}
