// GENERATED by flxc — the app route table.
// Do not edit by hand — your changes will be overwritten.

import 'package:flx/flx.dart';
import 'profile.dart';
import 'settings.dart';
import 'todos.dart';
import 'user.dart';

/// Every @page composable, keyed by its route pattern.
final appRoutes = <RouteDef>[
  RouteDef('/profile', (params) => const ProfileScreen()),
  RouteDef('/settings', (params) => const SettingsScreen()),
  RouteDef('/todos', (params) => const TodosScreen()),
  RouteDef('/user/:id', (params) => UserScreen(id: params['id'] ?? '')),
];

