// GENERATED by flxc from settings.flx.
// Do not edit by hand — your changes will be overwritten.
// ignore_for_file: unused_import, prefer_const_constructors,
// ignore_for_file: unnecessary_brace_in_string_interps,
// ignore_for_file: prefer_single_quotes, directives_ordering,
// ignore_for_file: lines_longer_than_80_chars,
// ignore_for_file: require_trailing_commas,
// ignore_for_file: prefer_const_literals_to_create_immutables

import 'package:flutter/material.dart';

import 'package:flx/flx.dart';

@page('/settings')
class SettingsScreen extends Composable {
  const SettingsScreen({super.key});

  @override
  Widget build(BuildContext context) {
    final scheme = useColorScheme();
    final size = useScreenSize();
    final nav = useNavigator();
    final dark = useState(false);

    return Scaffold(
      body: [
        Text("Settings", style: Styles.title),
        Text("Screen: ${size.width.toInt()} x ${size.height.toInt()}"),
        Text("Primary: ${scheme.primary}", style: Styles.caption),
        Text("Dark mode: ${dark.value}"),
        Button("Toggle dark mode", () {
          dark.value = !dark.value;
        }),
        Button("Back", () {
          nav.pop();
        }),
      ].column(gap: 12, main: MainAxisAlignment.center).padding(16),
    );
  }
}
