// GENERATED by flxc from todos.flx.
// Do not edit by hand — your changes will be overwritten.
// ignore_for_file: unused_import, prefer_const_constructors,
// ignore_for_file: unnecessary_brace_in_string_interps,
// ignore_for_file: prefer_single_quotes, directives_ordering,
// ignore_for_file: lines_longer_than_80_chars,
// ignore_for_file: require_trailing_commas,
// ignore_for_file: prefer_const_literals_to_create_immutables

import 'package:flutter/material.dart';

import 'package:flx/flx.dart';
import '../data/todos_view_model.dart';

@page('/todos')
class TodosScreen extends Composable {
  const TodosScreen({super.key});

  @override
  Widget build(BuildContext context) {
    final vm = useViewModel<TodosViewModel>();
    final nav = useNavigator();

    return Scaffold(
      body: [
        Text("Todos", style: Styles.title),
        Text("${vm.remaining} remaining", style: Styles.caption),
        if (vm.isEmpty) ...[
          Text("Nothing left to do", style: Styles.caption),
        ] else ...[
          for (final todo in vm.todos) ...[
            Text("${todo.done ? '✓' : '•'} ${todo.title}"),
          ],
        ],
        Button("Add a todo", () {
          vm.add("Task ${vm.todos.length + 1}");
        }),
        Button("Clear completed", () {
          vm.clearCompleted();
        }),
        Button("Back", () {
          nav.pop();
        }),
      ].column(gap: 12, main: MainAxisAlignment.center).padding(16),
    );
  }
}
