// GENERATED by flxc from user.flx.
// Do not edit by hand — your changes will be overwritten.
// ignore_for_file: unused_import, prefer_const_constructors,
// ignore_for_file: unnecessary_brace_in_string_interps,
// ignore_for_file: prefer_single_quotes, directives_ordering,
// ignore_for_file: lines_longer_than_80_chars,
// ignore_for_file: require_trailing_commas,
// ignore_for_file: prefer_const_literals_to_create_immutables

import 'package:flutter/material.dart';

import 'package:flx/flx.dart';

@page('/user/:id')
class UserScreen extends Composable {
  const UserScreen({required this.id, super.key});

  final String id;

  @override
  Widget build(BuildContext context) {
    final nav = useNavigator();

    return Scaffold(
      body: [
        Text("User profile", style: Styles.title),
        Text("User id: ${id}"),
        Text("Opened via route /user/${id}", style: Styles.caption),
        Button("Back", () {
          nav.pop();
        }),
      ].column(gap: 12, main: MainAxisAlignment.center).padding(16),
    );
  }
}
